### ISSUE TITLE
Cppcheck issue un Windows Launcher

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#1588]
**Describe the Bug**
The changes introduced in #1585 did raise new cppcheck failure:
```
src/webots/launcher/launcher.c:40:90: error: Null pointer dereference [nullPointer]
290    snprintf(message, sizeof(message), "%s failed with error %ld.\n%s%s%s", function, e, m, i, lf);
```

**Comment by DavidMansolino** [comment]
Another one from AppVeyor:
```
src\webots\launcher\launcher.c:40]: (portability) %ld in format string (no. 2) requires 'long' but the argument type is 'DWORD {aka unsigned long}'.
```
