### PR TITLE
Fix cppcheck warning

### LINKED ISSUE #1588: Cppcheck issue un Windows Launcher
**Describe the Bug**
The changes introduced in #1585 did raise new cppcheck failure:
```
src/webots/launcher/launcher.c:40:90: error: Null pointer dereference [nullPointer]
290    snprintf(message, sizeof(message), "%s failed with error %ld.\n%s%s%s", function, e, m, i, lf);
```

### PR DESCRIPTION
**Pull request by omichel**
Fix #1588.

### CODE REVIEW

**Comment by DavidMansolino** [comment]
The first issue is not fixed:
```
src/webots/launcher/launcher.c:40:90: error: Null pointer dereference [nullPointer]
290    snprintf(message, sizeof(message), "%s failed with error %ld.\n%s%s%s", function, e, m, i, lf);
```

**Comment by omichel** [comment]
It seems my local cppcheck is not working, I am investigating why...

**Comment by omichel** [comment]
👍
